# -*- coding: utf-8 -*-
"""Food Delivery Cost and Profitability Analysis using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kv3W6F-iVqQqmrFcqe4S1uvtXFl5LmRL

**Proposed Workflow for Food Delivery Cost and Profitability Analysis:**

1. **Data Collection**: Begin by compiling detailed data encompassing all facets of food delivery operations.
2. **Data Cleaning**: Address any inconsistencies, missing values, or irrelevant entries to ensure data quality.
3. **Feature Selection**: Identify and extract key variables that influence costs and profitability.
4. **Cost Breakdown**: Categorize the costs per order, distinguishing between fixed costs (e.g., packaging) and variable costs (e.g., delivery charges, discounts).
5. **Revenue Calculation**: Determine the revenue per order, considering both the gross order value (pre-discount) and commission fees.
6. **Profit Analysis**: Compute the profit for each order by subtracting total costs from revenue. Analyze the distribution to uncover patterns or areas of concern.
7. **Strategic Insights**: Develop actionable recommendations to improve profitability based on analytical findings.
8. **Scenario Simulation**: Model the financial impact of proposed changes—such as modifying discount structures or commission rates—using the collected data.
"""

import pandas as pd

food_orders = pd.read_csv("food_orders_new_delhi.csv")
print(food_orders.head())

print(food_orders.info())

"""DATA CLEANING"""

from datetime import datetime

# convert date and time columns to datetime
food_orders['Order Date and Time'] = pd.to_datetime(food_orders['Order Date and Time'])
food_orders['Delivery Date and Time'] = pd.to_datetime(food_orders['Delivery Date and Time'])

# first, let's create a function to extract numeric values from the 'Discounts and Offers' string
def extract_discount(discount_str):
    # Check if discount_str is a string to handle potential NaN values
    if isinstance(discount_str, str):
        if 'off' in discount_str:
            # Fixed amount off
            return float(discount_str.split(' ')[0])
        elif '%' in discount_str:
            # Percentage off
            return float(discount_str.split('%')[0])
        else:
            # No discount
            return 0.0
    else:
        # Handle non-string values (e.g., NaN) by returning 0
        return 0.0

# apply the function to create a new 'Discount Value' column
food_orders['Discount Percentage'] = food_orders['Discounts and Offers'].apply(lambda x: extract_discount(x))

# for percentage discounts, calculate the discount amount based on the order value
food_orders['Discount Amount'] = food_orders.apply(lambda x: (x['Order Value'] * x['Discount Percentage'] / 100)
                                                   if x['Discount Percentage'] > 1
                                                   else x['Discount Percentage'], axis=1)

# adjust 'Discount Amount' for fixed discounts directly specified in the 'Discounts and Offers' column
food_orders['Discount Amount'] = food_orders.apply(lambda x: x['Discount Amount'] if x['Discount Percentage'] <= 1
                                                   else x['Order Value'] * x['Discount Percentage'] / 100, axis=1)

print(food_orders[['Order Value', 'Discounts and Offers', 'Discount Percentage', 'Discount Amount']].head(), food_orders.dtypes)

"""**COST AND PROFITABILITY ANALYSIS**"""

# calculate total costs and revenue per order
food_orders['Total Costs'] = food_orders['Delivery Fee'] + food_orders['Payment Processing Fee'] + food_orders['Discount Amount']
food_orders['Revenue'] = food_orders['Commission Fee']
food_orders['Profit'] = food_orders['Revenue'] - food_orders['Total Costs']

# aggregate data to get overall metrics
total_orders = food_orders.shape[0]
total_revenue = food_orders['Revenue'].sum()
total_costs = food_orders['Total Costs'].sum()
total_profit = food_orders['Profit'].sum()

overall_metrics = {
    "Total Orders": total_orders,
    "Total Revenue": total_revenue,
    "Total Costs": total_costs,
    "Total Profit": total_profit
}

print(overall_metrics)

"""**Visualizing Cost, Revenue, and Profit Distribution:**
To gain deeper insights into the distribution and composition of costs, revenue, and profit, we will use the following visualizations:

1. **Profit Distribution Histogram**:  
   Plot a histogram of profit per order to understand the spread of profitable versus unprofitable transactions.

2. **Cost Composition Pie Chart**:  
   Use a pie chart to illustrate the relative proportions of total costs, including:
   - Delivery fees  
   - Payment processing fees  
   - Discounts applied

3. **Revenue vs. Cost vs. Profit Bar Chart**:  
   Create a bar chart to compare the aggregate values of:
   - Total revenue  
   - Total costs  
   - Total profit

These visual tools will help in identifying key drivers of profitability and spotting inefficiencies or outliers in the delivery process.
"""

import matplotlib.pyplot as plt

# histogram of profits per order
plt.figure(figsize=(10, 6))
plt.hist(food_orders['Profit'], bins=50, color='skyblue', edgecolor='black')
plt.title('Profit Distribution per Order in Food Delivery')
plt.xlabel('Profit')
plt.ylabel('Number of Orders')
plt.axvline(food_orders['Profit'].mean(), color='red', linestyle='dashed', linewidth=1)
plt.show()

# pie chart for the proportion of total costs
costs_breakdown = food_orders[['Delivery Fee', 'Payment Processing Fee', 'Discount Amount']].sum()
plt.figure(figsize=(7, 7))
plt.pie(costs_breakdown, labels=costs_breakdown.index, autopct='%1.1f%%', startangle=140, colors=['tomato', 'gold', 'lightblue'])
plt.title('Proportion of Total Costs in Food Delivery')
plt.show()

# bar chart for total revenue, costs, and profit
totals = ['Total Revenue', 'Total Costs', 'Total Profit']
values = [total_revenue, total_costs, total_profit]

plt.figure(figsize=(8, 6))
plt.bar(totals, values, color=['green', 'red', 'blue'])
plt.title('Total Revenue, Costs, and Profit')
plt.ylabel('Amount (INR)')
plt.show()

"""**A New Strategy for Profits**"""

# filter the dataset for profitable orders
profitable_orders = food_orders[food_orders['Profit'] > 0]

# calculate the average commission percentage for profitable orders
profitable_orders['Commission Percentage'] = (profitable_orders['Commission Fee'] / profitable_orders['Order Value']) * 100

# calculate the average discount percentage for profitable orders
profitable_orders['Effective Discount Percentage'] = (profitable_orders['Discount Amount'] / profitable_orders['Order Value']) * 100

# calculate the new averages
new_avg_commission_percentage = profitable_orders['Commission Percentage'].mean()
new_avg_discount_percentage = profitable_orders['Effective Discount Percentage'].mean()

print(new_avg_commission_percentage, new_avg_discount_percentage)

"""**Insights from Profitable Orders: Identifying the “Sweet Spot”**

An in-depth analysis of profitable orders reveals new average values that may serve as optimal targets for key pricing levers:

- **Average Commission Percentage**: **30.51%**  
- **Average Discount Percentage**: **5.87%**

These figures diverge significantly from the overall averages observed across all orders:

- The **higher commission percentage** in profitable orders suggests that a commission rate closer to 30% may be a strong driver of profitability.
- Conversely, the **lower discount percentage** indicates that minimizing discounts—without severely impacting order volume—can positively influence profit margins.

**Strategic Recommendation:**  
To enhance overall profitability, consider adjusting pricing strategies to aim for a **commission rate around 30%** and a **discount rate near 6%**. This balance could maintain competitiveness while significantly improving financial performance.
"""

# simulate profitability with recommended discounts and commissions
recommended_commission_percentage = 30.0  # 30%
recommended_discount_percentage = 6.0    # 6%

# calculate the simulated commission fee and discount amount using recommended percentages
food_orders['Simulated Commission Fee'] = food_orders['Order Value'] * (recommended_commission_percentage / 100)
food_orders['Simulated Discount Amount'] = food_orders['Order Value'] * (recommended_discount_percentage / 100)

# recalculate total costs and profit with simulated values
food_orders['Simulated Total Costs'] = (food_orders['Delivery Fee'] +
                                        food_orders['Payment Processing Fee'] +
                                        food_orders['Simulated Discount Amount'])

food_orders['Simulated Profit'] = (food_orders['Simulated Commission Fee'] -
                                   food_orders['Simulated Total Costs'])

# visualizing the comparison
import seaborn as sns

plt.figure(figsize=(14, 7))

# actual profitability
sns.kdeplot(food_orders['Profit'], label='Actual Profitability', fill=True, alpha=0.5, linewidth=2)

# simulated profitability
sns.kdeplot(food_orders['Simulated Profit'], label='Estimated Profitability with Recommended Rates', fill=True, alpha=0.5, linewidth=2)

plt.title('Comparison of Profitability in Food Delivery: Actual vs. Recommended Discounts and Commissions')
plt.xlabel('Profit')
plt.ylabel('Density')
plt.legend(loc='upper left')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


# Correlation Heatmap
corr = food_orders.corr(numeric_only=True)
sns.heatmap(corr[['Profit']], annot=True, cmap='coolwarm')
plt.title("Feature Correlation with Profit")
plt.show()

# Time-based Feature: Delivery Duration
food_orders['Delivery Duration (min)'] = (food_orders['Delivery Date and Time'] - food_orders['Order Date and Time']).dt.total_seconds() / 60
sns.boxplot(x=food_orders['Order Date and Time'].dt.dayofweek, y=food_orders['Delivery Duration (min)'])
plt.title("Delivery Duration by Day of Week")
plt.xlabel("Day of Week (0=Monday)")
plt.ylabel("Delivery Duration (min)")
plt.show()

import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

# 1. Customer Lifetime Value
cltv = food_orders.groupby('Customer ID').agg({
    'Order ID': 'count',
    'Profit': 'sum',
    'Order Value': 'sum'
}).rename(columns={'Order ID': 'Total Orders', 'Profit': 'Total Profit'})
print(cltv.head())

# Refund/Chargeback Analysis
refund_rate = food_orders['Refunds/Chargebacks'].sum() / food_orders['Order Value'].sum()
print(f"Overall refund rate: {refund_rate:.2%}")

# Delivery Time vs Profitability
food_orders['Delivery Duration (min)'] = (food_orders['Delivery Date and Time'] - food_orders['Order Date and Time']).dt.total_seconds() / 60
plt.figure(figsize=(10, 6))
sns.scatterplot(data=food_orders, x='Delivery Duration (min)', y='Profit')
plt.title('Delivery Duration vs Profit')
plt.show()

# Restaurant Scorecard
restaurant_perf = food_orders.groupby('Restaurant ID').agg({
    'Order ID': 'count',
    'Profit': 'mean',
    'Delivery Duration (min)': 'mean',
    'Refunds/Chargebacks': 'sum'
}).rename(columns={'Order ID': 'Total Orders', 'Profit': 'Avg Profit'})
print(restaurant_perf.head())

# Payment Method Insights
payment_stats = food_orders.groupby('Payment Method').agg({
    'Order ID': 'count',
    'Profit': 'mean',
    'Refunds/Chargebacks': 'sum'
}).rename(columns={'Order ID': 'Total Orders', 'Profit': 'Avg Profit'})
payment_stats.plot(kind='bar', figsize=(10, 6))
plt.title('Payment Method Insights')
plt.ylabel('Values')
plt.show()

# Profitability Buckets
food_orders['Profit Category'] = pd.qcut(food_orders['Profit'], q=3, labels=['Low', 'Medium', 'High'])
sns.boxplot(x='Profit Category', y='Order Value', data=food_orders)
plt.title("Order Value by Profitability Bucket")
plt.show()

# Customer Segmentation with Clustering
cust_seg = food_orders.groupby('Customer ID').agg({
    'Order Value': 'mean',
    'Discount Amount': 'mean',
    'Refunds/Chargebacks': 'sum',
    'Profit': 'mean'
})
scaler = StandardScaler()
cust_scaled = scaler.fit_transform(cust_seg)
km = KMeans(n_clusters=3, random_state=42)
cust_seg['Cluster'] = km.fit_predict(cust_scaled)
px.scatter(cust_seg, x='Order Value', y='Profit', color=cust_seg['Cluster'].astype(str), title='Customer Segments').show()

# Time Series Trends
food_orders['Week'] = food_orders['Order Date and Time'].dt.to_period('W').astype(str)
weekly = food_orders.groupby('Week').agg({'Order ID': 'count', 'Profit': 'sum'})
weekly.plot(figsize=(12, 6))
plt.title('Weekly Order Volume & Profit')
plt.show()

food_orders['Order Hour'] = food_orders['Order Date and Time'].dt.hour
food_orders['Order Weekday'] = food_orders['Order Date and Time'].dt.day_name()
plt.figure(figsize=(12, 6))
sns.heatmap(food_orders.pivot_table(index='Order Weekday', columns='Order Hour', values='Order ID', aggfunc='count'), cmap='YlGnBu')
plt.title('Order Density Heatmap (Hour vs Weekday)')
plt.show()

# Anomaly Detection
features = food_orders[['Order Value', 'Profit', 'Delivery Duration (min)', 'Refunds/Chargebacks']].fillna(0)
anomaly_model = IsolationForest(contamination=0.01, random_state=42)
food_orders['Anomaly'] = anomaly_model.fit_predict(features)
sns.scatterplot(data=food_orders, x='Order Value', y='Profit', hue='Anomaly', palette='coolwarm')
plt.title('Anomaly Detection in Orders')
plt.show()